/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as SignupImport } from './routes/signup'
import { Route as CategoryImport } from './routes/category'
import { Route as IndexImport } from './routes/index'
import { Route as ProductCreateImport } from './routes/product.create'

// Create/Update Routes

const UploadRoute = UploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const CategoryRoute = CategoryImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductCreateRoute = ProductCreateImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/product/create': {
      id: '/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof ProductCreateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/product/create': typeof ProductCreateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/product/create': typeof ProductCreateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/category': typeof CategoryRoute
  '/signup': typeof SignupRoute
  '/upload': typeof UploadRoute
  '/product/create': typeof ProductCreateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/category' | '/signup' | '/upload' | '/product/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category' | '/signup' | '/upload' | '/product/create'
  id: '__root__' | '/' | '/category' | '/signup' | '/upload' | '/product/create'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoryRoute: typeof CategoryRoute
  SignupRoute: typeof SignupRoute
  UploadRoute: typeof UploadRoute
  ProductCreateRoute: typeof ProductCreateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoryRoute: CategoryRoute,
  SignupRoute: SignupRoute,
  UploadRoute: UploadRoute,
  ProductCreateRoute: ProductCreateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/category",
        "/signup",
        "/upload",
        "/product/create"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/category": {
      "filePath": "category.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/upload": {
      "filePath": "upload.tsx"
    },
    "/product/create": {
      "filePath": "product.create.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
